services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_HOST}
    ports:
      - "15433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network


  web:
    build: ./web
    command: gunicorn Food_Waste_Fridge.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "16701:80"
    depends_on:
      - web
    volumes:
      - static_volume:/app/static
    networks:
      - app-network

# 定義網路
networks:
  app-network:

# 定義命名卷
volumes:
  postgres_data:
    external: True
  static_volume: