version: '3.8'

services:
  web:
    build: ./web
    volumes:
      - static_volume:/app/static
    expose:
      - 8000

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - static_volume:/app/static

volumes:
  static_volume:
