# Generated by Django 5.2 on 2025-05-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_fridge", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="img_path",
            field=models.ImageField(blank=True, null=True, upload_to="food_images/"),
        ),
    ]
